### ISSUE TITLE
Allow connections to mongo Atlas

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/Mongo_Toolkit#145]
#### Description:
At present the `MongoAdapter` forces all `connectionString`s to start with "mongodb://".

If you work with mongo Atlas the connection string typically starts with "mongodb+srv://"

At present we cannot connect to the Atlas service with the Mongo_Toolkit.

It would be very cool to allow this particularly for prototyping work using the mongodb Atlas free tier (which is limited to 512MB of storage, shared vCPU and RAM, 100 max connections, and a limit of one M0 cluster.) 

And for others working with Atlas as their standard mongodb platform.

I've had a go a connecting and pushing and pulling all seems good and faster than my experience with SRV-BHOM01
![image](https://user-images.githubusercontent.com/6618854/132844957-96d3074d-a957-4fd2-a44d-a0016fb4fdeb.png)

Just wondering if there is any good reason why not to allow these connections? @adecler @al-fisher @FraserGreenroyd ?

**Comment by al-fisher** [comment]
Sounds good to me. Good to include as ability as additional option
