### ISSUE TITLE
Mongo_Toolkit: MongoMatchList won't' allow matching strings

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/Mongo_Toolkit#32]
Probably need a MongoMatchText one as well

**Comment by adecler** [comment]
I am not sure I understand the title and the description doesn't provide context. 
I cannot replicate so will close for now as the [related PR](https://github.com/BHoM/Mongo_Toolkit/pull/54) was also closed. This can be re-open if things change but most likely better to open new issues.
