### ISSUE TITLE
Mongo_Toolkit: Ask IT, or find a way to expose our LAN IP address internally

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Mongo_Toolkit#39]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Not in roadmap and not been required in several years.
