### ISSUE TITLE
Mongo_Toolkit: create proper MongoConfigobject

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Mongo_Toolkit#67]
#### Description:

To host `Tag` and `Replace` properties. 
These properties are already used, but you need to know what they are, since the only way to feed them to the adapter is through a keyvalue pair collection.

**Comment by peterjamesnugent** [comment]
Hi @epignatelli can you share a script/GIF showing the current workaround please.

**Comment by epignatelli** [comment]
Hey @peterjamesnugent !
The code I am talking about is here: https://github.com/BHoM/Mongo_Toolkit/blob/92cbbca1ca2d96264d6cfdd274efe85896bbcc26/Mongo_Adapter/AdapterActions/Push.cs#L39-L53

The graph is something like this:
![image](https://user-images.githubusercontent.com/26899347/69444147-aa58b200-0d47-11ea-9466-c3acad894131.png)

**Comment by peterjamesnugent** [comment]
Thanks @epignatelli!

**Comment by epignatelli** [comment]
Hi @alelom - with the refactoring this could be closed, right?

**Comment by epignatelli** [comment]
After a chat with @alelom - this is solved by https://github.com/BHoM/Mongo_Toolkit/pull/82
