### ISSUE TITLE
BH.Engine.Mongo Convert

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/Mongo_Toolkit#72]
#### Description:
floating point issue with
public static BsonDocument ToMongoQuery(this FilterRequest query)

#### How to replicate:
When using this:
FilterRequest filterRequest = new FilterRequest();
            filterRequest.Equalities.Add("lat", 4.1);

ToMongoQuery returns
{{ "lat" : 4.0999999999999996 }}

#### Expected behaviour:
ToMongoQuery returns
{{ "lat" : 4.1}}

**Comment by adecler** [comment]
I will try to have a look at that today or tomorrow. 
One advise I can give straight away is to start using `CustomRequest` for pulling data so you can better control your queries. Equality of doubles is always going a  fairly dangerous things to do regardless of the context. You can't use `CustomRequest` in Delete yet, but delete should be something yuo pretty much never need thank to the way Push is already replacing data with the same tag.

**Comment by adecler** [comment]
I've just had a look and the problems happens in the Mongo.Bson library itself. AS i mentioned above, that library is not really to blame either as doubles cannot be guarantied to maintain their exact value.  
You can easily solve your problem by doing the following:
```
filterRequest.Equalities.Add("lat", (decimal)4.1);
```

Can you close this issue if you are happy with that solution?

**Comment by rolyhudson** [comment]
Sounds good to me. Thanks for the explanation.
