### ISSUE TITLE
Mongo Adapter default Replace behaviour 

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/Mongo_Toolkit#93]
#### Description:
Per conversation with @alelom and @epignatelli regarding Mongo_Adapter actionConfig default behaviors. By default the Mongo_Adapter will overwrite any existing data within a collection. I would argue this behavior is not intuitive and may lead to confusion since the MongoConfig input param 'Replace' is set to False by default. 

#### Steps to reproduce:
Push any data to be appended to any collection to MongoDB without using Mongo actionConfig.

#### Expected behaviour:
Expect to append data within collection, or at least concurrence between default adapter functionality and MongoConfig.

**Comment by alelom** [comment]
@adecler I did the Adapter Aligment in this toolkit. I probably have set the default value of the Replace boolean in the MongoConfig with the incorrect value - should it be `true` instead? 
Do we want Replace to be done by default when pushing? I am simply asking to know what's best.
Thanks.

**Comment by jamesramsden-bh** [comment]
Bump.
@alelom , just stumbled across this issue after trying Mongo Toolkit for the first time in GH the other day. The default overwrite behaviour is indeed unintuitive, and a default behaviour of 'append' would be much more sensible.
